# Tensores

Los tensores son una estructura de datos especializada muy similar a las matrices y arrays.
En PyTorch, se usan los tensores para codificar las entradas y salidas de un modelo, así como los parámetros del modelo.

Los tensores son muy similares a los ndarrays de NumPy, excepto que los tensores pueden ejecutarse en GPUs para acelerar la computación.

Si estás familiarizado con los ndarrays, te sentirás como en casa.
Si no, sigue este rápido recorrido por la API.

In [1]:
# Importamos torch y numpy
import torch
import numpy as np

### Inicializar un Tensor

Podemos inicializar tensores de varias formas:
- Desde un objeto Python
- Desde un array de Numpy
- Desde otro tensor
- Utilizando funciones torch

In [2]:
# Creamos un tensor
data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] # Tensor de 1x10
x_data = torch.tensor(data)
print(x_data)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [3]:
# Creamos un tensor con numpy
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
x_numpy = torch.tensor(data)
print(x_numpy)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=torch.int32)


In [4]:
# Creando un tensor a partir de otro tensor
y = torch.tensor(x_numpy)
print(y)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=torch.int32)


C:\Users\POMPAS\AppData\Local\Temp\ipykernel_8528\822525755.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y = torch.tensor(x_numpy)


In [5]:
# Deinimos una forma
shape = (2, 3,)

# Creanmos un tensor de ceros
x_ones = torch.zeros(shape)
print(f"Ones Tensor: \n {x_ones} \n")

# Creando un tensor aleatorio
x_rand = torch.rand(shape)
print(f"Random Tensor: \n {x_rand} \n")

# Creando un tensor de unos
ones_tensor = torch.ones(shape)
print(f"Ones Tensor: \n {ones_tensor} \n")

Ones Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 

Random Tensor: 
 tensor([[0.5407, 0.5803, 0.5376],
        [0.9664, 0.1158, 0.8537]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 



### Atributos de un tensor


In [6]:
# Creamos un tensoor de 3 filas y 4 columnas
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}") # Tamanio del tensor
print(f"Datatype of tensor: {tensor.dtype}") # Tipo de dato
print(f"Device tensor is stored on: {tensor.device}") # Dispositivo

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### Tensores con CUDA


Si en nuestro PC o maquina virtual, tenemos soporte CUDA, podemos utilizar este servicio para optimizar operaciones entre tensores, entre las que se incluyen la transposición, la indexación, el troceado, las operaciones matemáticas, el álgebra lineal y el muestreo aleatorio, entre otras.

In [7]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
tensor = tensor.to(device)
print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0
